### ISSUE TITLE
Add support for multiple host

### ISSUE THREAD

**Issue by PatrikValo** [PatrikValo/ssh-automation#13]
Opportunity to define multiple groups of hosts. 

For example:
```yaml
hosts:
    - group: "ubuntu"
    - addr:
        - "192.168.5.125"
        - "192.168.5.126"
    - group: "fedora"
    - addr:
        - "192.168.5.127"
        - "192.168.5.128"
    - group: "db"
    - addr:
        - "192.168.5.125"
        - "192.168.5.127"  
```

In task there would be possibility to reference each group for given task.
